In [33]:
import math
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
import torchtext
import matplotlib.pyplot as plt

In [32]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = get_tokenizer("basic_english")
class EEPD_Dataset(Dataset):
    def __init__(self, x, y):
        
        self.text = torch.tensor(x).to(device)
        self.label = torch.tensor(y).to(device)
        self.n_samples = x.shape[0]


    def __getitem__(self, index):
        return self.text[index], self.label[index]
    
    def __len__(self):
        return self.n_samples



In [23]:

data = 'data/WASSA23_conv_level_with_labels_train.tsv'

def yield_tokens(text_data):
    for text in text_data:
        yield tokenizer(text)

xy = pd.read_table(data, header=0)
new_col = []
for names in xy.columns:
    new_col.append(names.strip())
xy.columns = new_col
x, y = xy.loc[:, 'text'], xy.loc[:, ['EmotionalPolarity', 'Emotion', 'Empathy']]
y = np.array(y)


padd_to_tensor = torchtext.transforms.ToTensor(padding_value=0)
vocab = build_vocab_from_iterator(yield_tokens(x), specials=["<unk>"])
vocab.set_default_index(vocab["<unk>"])
train_x, train_y = [], []
for text, label in zip(x, y):
    x_tokens = vocab(tokenizer(text))
    y_label = np.array(label)
    train_x.append(x_tokens)
    train_y.append(y_label)
train_x = padd_to_tensor(train_x)



In [24]:
for i in range(5):
    x = train_x[i]
    print(x)
max_row = max(train_x, key=len)
print(f'max is: {len(max_row)}, x: {max_row}')

tensor([ 2, 65, 82, 72, 23,  3, 25,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0])
tensor([  7,   6,  17, 183,   1,  32, 121,   3,  25,  24,   3, 144,  46,  74,
         42,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 

In [27]:
data = 'data/WASSA23_conv_level_with_labels_train.tsv'
dataset = EEPD_Dataset(train_x, train_y)
dataloader = DataLoader(dataset=dataset, batch_size=1, shuffle=False)
data_iter = iter(dataloader)

for i in range(2):
    feature,label = next(data_iter)
feature,label

C:\Users\AttahiruJibril\AppData\Local\Temp\ipykernel_6172\589271042.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.text = torch.tensor(x).to(device)


(tensor([[  7,   6,  17, 183,   1,  32, 121,   3,  25,  24,   3, 144,  46,  74,
           42,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0]]),
 tensor([[2.0000, 4.0000, 3.3333]], dtype=torch.float64))

In [28]:
input_size = 

print(n_samples, n_iterations)

for epoch in range(n_epochs):
    for i, (input, labels) in enumerate(dataloader):
        print(f'Epoch: {epoch+1}/{n_epochs} | step{i+1}/{n_iterations}')

8776 2194
Epoch: 1/8 | step1/2194
Epoch: 1/8 | step2/2194
Epoch: 1/8 | step3/2194
Epoch: 1/8 | step4/2194
Epoch: 1/8 | step5/2194
Epoch: 1/8 | step6/2194
Epoch: 1/8 | step7/2194
Epoch: 1/8 | step8/2194
Epoch: 1/8 | step9/2194
Epoch: 1/8 | step10/2194
Epoch: 1/8 | step11/2194
Epoch: 1/8 | step12/2194
Epoch: 1/8 | step13/2194
Epoch: 1/8 | step14/2194
Epoch: 1/8 | step15/2194
Epoch: 1/8 | step16/2194
Epoch: 1/8 | step17/2194
Epoch: 1/8 | step18/2194
Epoch: 1/8 | step19/2194
Epoch: 1/8 | step20/2194
Epoch: 1/8 | step21/2194
Epoch: 1/8 | step22/2194
Epoch: 1/8 | step23/2194
Epoch: 1/8 | step24/2194
Epoch: 1/8 | step25/2194
Epoch: 1/8 | step26/2194
Epoch: 1/8 | step27/2194
Epoch: 1/8 | step28/2194
Epoch: 1/8 | step29/2194
Epoch: 1/8 | step30/2194
Epoch: 1/8 | step31/2194
Epoch: 1/8 | step32/2194
Epoch: 1/8 | step33/2194
Epoch: 1/8 | step34/2194
Epoch: 1/8 | step35/2194
Epoch: 1/8 | step36/2194
Epoch: 1/8 | step37/2194
Epoch: 1/8 | step38/2194
Epoch: 1/8 | step39/2194
Epoch: 1/8 | step40/2194